fields:
  - name: id
    type: int
    unique: true
    nullable: false
    range:
      min: 1
      max: 10000

  - name: name
    type: string
    nullable: false
    length:
      min: 5
      max: 20
    faker_template: name

  - name: email
    type: string
    nullable: false
    unique: true
    faker_template: email

  - name: age
    type: int
    nullable: false
    range:
      min: 18
      max: 80

  - name: salary
    type: float
    nullable: true
    range:
      min: 30000.0
      max: 150000.0
    precision: 2
    null_rate: 0.05

  - name: department
    type: category
    nullable: false
    values:
      - Engineering
      - Marketing
      - Sales
      - HR
      - Finance

  - name: hire_date
    type: date
    nullable: false
    range:
      start: '2020-01-01'
      end: '2024-12-31'
    format: '%Y-%m-%d'

  - name: notes
    type: string
    nullable: true
    length:
      min: 10
      max: 100
    null_rate: 0.3 